name: CI and CD data model

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - staging

jobs:
  retraining_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest
    env:
      repo_token: ${{ secrets.GITHUBTOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run:
          pip3 install -r requirements.txt

      - name: Execute the training model
        run: |
          python3 train_model.py

      - name: Generating report
        run: |
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data visualization" >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          cml-send-comment report.md
  build_docker_image:
    needs: retraining_model
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t greivin99/trabajo_final_mlops .

      - name: Docker push to Dockerhub
        run: docker push greivin99/trabajo_final_mlops


      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_PRIVATE_KEY }}
         script: |
                  docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
                  if docker ps --all | grep trabajo_final_mlops; then
                    docker stop trabajo_final_mlops
                    docker rm trabajo_final_mlops
                  fi
                  
                  docker pull greivin99/trabajo_final_mlops
                  docker run -d --name trabajo_final_mlops -p 8001:8000 greivin99/trabajo_final_mlops
